#!/usr/bin/env bash

set -euo pipefail
THIS_DIR="$(dirname "$(realpath "$0")")"

mapfile -t languages < <(ls "$THIS_DIR" | awk '/0-template/ {print substr($0, 12)}')

printf "Pick a language:\n"
for lang in "${languages[@]}"; do
  printf "| %s\n" "$lang"
done
read -p "==> " language
template_dir="0-template-$language"
if [[ ! -d "$THIS_DIR/$template_dir" ]]; then
  printf "no lang template for %s\n" "$language"
  exit 1
fi

printf "\nPick directory name\n"
read -p "==> " extract_dir
extract_dir="$THIS_DIR/$extract_dir"

mkdir -p "$extract_dir"
cp -i "$template_dir/main.$lang" "$extract_dir"
if [[ -f "$template_dir/Makefile" ]]; then
  ln -s "../$template_dir/Makefile" "$extract_dir/Makefile"
fi
